### ISSUE TITLE
Should we squeeze the dimensions if eval is called with a single value?

### ISSUE THREAD

**Issue by faymanns** [EPFL-Center-for-Imaging/splinebox#14]
`spline.eval(0)` returns an array of shape (1, n), where n is the is the dimensionality of the codomain. Should it return an array of shape (n) instead.

Note that this might cause problems elsewhere in the code base.

**Comment by vuhlmann** [comment]
In theory I don't see why we shouldn't squeeze the array, but the way I initially implemented things definitely assumed we were always dealing with a 2D array. So things downstream may break as you predicted.

**Comment by faymanns** [comment]
Added in 3f8d474 and b7af757
