### ISSUE TITLE
Name and architecture changes to handed-over version

### ISSUE THREAD

**Issue by edwardando** [EPFL-Center-for-Imaging/splinebox#2]
@vuhlmann  Can you confirm
- [x]  Basis functions (file renamed from `splineBasis.py` to `basis_functions.py`)
  - [x] Keys → CatmullRom
  - [x] EM → Exponential
  - [x] #3
  - [x] HE3 → ExponentialHermite ???
- [x] `class SplineGenerator` → `class BasisFunction`
  - [x] `SplineGenerator.value()` and derivatives → `BasisFunction.eval(X, derivative=0,1,2)` a little nod to `scipy.interpolate.splev` ← and this will likely accept a numpy array
  - [x] filterPeriodic() → filter_periodic()
  - [x] filterSymmetric() → filter_symmetric()
  - [x] refinementMask() → refinement_mask()

- [x] Spline Curves (file renamed from `splineCurves.py` to `spline_curves.py`) 
  - [x] #4
  - [x] #5
  - [x] #6
  - [x] `SplineCurve.getCoefsFromBinaryMask()` → dropped since easy to do externally and allows up to drop skimage dep

**Comment by faymanns** [comment]
* Derivative parameter introduced in `BasisFunction.eval` bdbded5
* Renamed `filterPeriodic`, `filterSymmetric`, `refinementMask` in 4048adf

**Comment by faymanns** [comment]
* `SplineCurve.parameterToWorld()` -> `Spline.eval(X, derivative=0, 1, 2)` implemented in 387c846
* Droped `getCoefsFromBinaryMask()` in 387c846
