### ISSUE TITLE
how to save/load splines?

### ISSUE THREAD

**Issue by kevinyamauchi** [EPFL-Center-for-Imaging/splinebox#24]
Hello! Thanks for the nice library. I am sorry if I missed it, but what is the recommended way to save/store fitted splines? It seems like pickling would work, but it would be nice if there were a way to serialize into something that is interoperable across languages (e.g., JSON). If that isn't currently possible, is something like that on the roadmap?

Thanks!

**Comment by faymanns** [comment]
This is not currently implemented but it would be easy to add something like that.
Do you have some specific language/library in mind?

The spline is fully defined by the choice of basis function, the control points, and its periodicity, i.e. is it closed or not.
A JSON with a string for the name of the basis function, an array of the control points and a bool for the periodicity should be sufficient.

**Comment by kevinyamauchi** [comment]
Thanks for the quick reply!

> Do you have some specific language/library in mind?

Sorry, I don't have anything in particular in mind at the moment 😬. I guess my feeling is that pickling is a bit brittle (e.g., changes in the model in future versions may not be compatible) and it would be nice to be able to read into other platforms as the need arises (I'm not sure if there are standard spline formats). I totally understand if that is not a priority right now.

> The spline is fully defined by the choice of basis function, the control points, and its periodicity, i.e. is it closed or not.
A JSON with a string for the name of the basis function, an array of the control points and a bool for the periodicity should be sufficient.

This would be sufficient for our purposes. Something like a `Spline.to_json()` method and `Spline.from_json()` constructor would be awesome!

The next couple of weeks are pretty busy for me, but I could give it a go in early October if you'd find that helpful.

**Comment by faymanns** [comment]
> Sorry, I don't have anything in particular in mind at the moment.

No problem, I fully agree that pickling is not a good option.

> I'm not sure if there are standard spline formats.

I think there is not standard format for individual splines, but we might be able to use a CAD file formats such as dxf or step. However, those seem to be limited to 2D and 3D. That being said, a simple json file is much easier to read by a human and would not require any new dependencies. I would go for the JSON first and add other formats later on if there is a need for it.

> Something like a Spline.to_json() method and Spline.from_json() constructor would be awesome!

Agreed! That way we would end up with one file per spline. I supposed we would need a helper function that is not a class method to save multiple splines in one file.

> The next couple of weeks are pretty busy for me, but I could give it a go in early October if you'd find that helpful.

That sounds great! October is quite busy for me but I might be able to get started on this before.

I supposed it would be great if these files could be opened with napari. Afik there is no spline layer type or similar and it is not (yet?) possible to create new layer types as part of a plugin. (I'm thinking about creating a splinebox napari plugin.)

**Comment by kevinyamauchi** [comment]
> Agreed! That way we would end up with one file per spline. I supposed we would need a helper function that is not a class method to save multiple splines in one file.

yes, that would be nice to have a function to save a collection of splines! 

> I supposed it would be great if these files could be opened with napari. Afik there is no spline layer type or similar and it is not (yet?) possible to create new layer types as part of a plugin. (I'm thinking about creating a splinebox napari plugin.)

Yes this would be great! There isn't a spline layer yet, but I believe somebody in @vuhlmann 's group was working on a napari plugin for visualizing splines. Perhaps that would be a good starting point.

**Comment by faymanns** [comment]
I have created a first pull request (#29) for saving and loading individual splines.
@kevinyamauchi can you take a look when you have time and let me know your thoughts?

One potential downside I came a cross when testing is that we lose double precision when saving the splines as json.
Probably not a problem but good to keep in mind.

**Comment by kevinyamauchi** [comment]
Thanks! Just had a look and left a comment.

> One potential downside I came a cross when testing is that we lose double precision when saving the splines as json.
Probably not a problem but good to keep in mind.

Ah this is a good point. For my applications this wouldn't matter, but I agree it's good to keep in mind as others might have an issue with it.

**Comment by faymanns** [comment]
I just merged the pull request (#29).

FYI: I have started working on [napari-splinebox](https://github.com/EPFL-Center-for-Imaging/napari-splinebox) and plan to include a reader and writer that can open the json files in napari directly.
