### ISSUE TITLE
`SplineCurve.getCoefsFromKnots()` → `Spline.fit()` ← Do you agree??

### ISSUE THREAD

**Issue by vuhlmann** [EPFL-Center-for-Imaging/splinebox#5]

**Comment by vuhlmann** [comment]
No, this one is really converting knots to control points - I wouldn't call it "fit" because fitting is the process of getting the spline parameters (either the control points or the knots) from the data to be interpolated

**Comment by faymanns** [comment]
I have spent some more time thinking about the naming of this function and I think the cleanest would be to drop it completely and just use class attributes and the property decorator.
From the user's perspective this would work as follows:

The `coeffs` attribute would have standard getter and setter behaviour: 
* `spline.coeffs = coeffs` can be used to set the coefficients explicitly.
* `coeffs = spline.coeffs` returns the current coefficients.

The `knots` are behaving the same way from the user perspective but internally modify the coefficients:
* `spline.knots = knots` will update the coefficients to match the knots provided. The knots are not internally stored. This would replace `getCoefsFromKnots()`.
* `knots = spline.knots` will return the knots based on the coefficients of the spline object. Internally this would be implemented as `spline.eval(np.arange(M))`.

Below are some pros and cons I see for this approach:

**Pros:**
1. This approach ensures that the `spline` object's integrity is preserved at all times, i.e. it is not possible to set conflicting information for the knots and coefficients.
2. It is easy to update a spline's coefficients, e.g. for active contours.
3. It makes it explicit that we are setting a class attribute, while `getCoefsFromKnots` suggest that we are returning a class attribute.
4. It is short to write.

**Cons:**
1. It is not explicitly clear that setting the `knots` attribute also changes the `coeffs` attribute.

Do you agree @vuhlmann and @edwardando?

**Comment by edwardando** [comment]
I'm pretty convinced this is convenient, *for my use* but Virginie's input is super precious here!

**Comment by faymanns** [comment]
I implemented this in 5427c96, but kept the functions `getCoefsFromKnots` and `getKnotsFromCoefs` for now.

**Comment by vuhlmann** [comment]
This is an excellent solution! 

I don't think we need something explicit in the code indicating that setting the knots attribute also changes the coeffs attribute - we only need documentation making it clear that these two sets of parameters are in 1-to-1 correspondence (I know, this is my homework)

**Comment by faymanns** [comment]
I removed the remaining `getCoefsFromKnots`  and `getKnotsFromCoefs` in cc2effb67e876a7e678267b2abf3c7a986e25266 and will close this issue since we have converged on a solution.
