### ISSUE TITLE
Defaults for arc_length function

### ISSUE THREAD

**Issue by faymanns** [EPFL-Center-for-Imaging/splinebox#8]
In the original version the function signature was `arc_length(self, t0, tf=None)`, where `t0` is the starting point and `tf` is the final point in parameters space. When `tf` is not set the integration is done from `t0` to the end of the spline, i.e. `tf=M`.
To me this seems counter intuitive. Especially because you have to call `spline.arc_length(0)` to obtain the arc length of the entire spline.
Without looking at the documentation, I would expect the integration to go from 0 to `t`, with the option to specify a different starting point.

I propose the following new function signature:
`arc_length(self, stop=-1, start=0)` with the following behaviour:
* `arc_length()` return the arc length of the entire spline
* `arc_length(10)` returns the arc length between parameter values of t=0 and t=10
* `arc_length(start=5)` returns the arc length value between parameter values t=5 and the end of the spline

The only con I can come up with is that `stop` comes before `start` in the parameters which allows users to write code like this:
`arc_length(10, 5)`
This can be avoided by writing `arc_length(start=5, stop=10)` which is more explicit and therefore better according to the zen of python.

Any thoughts @vuhlmann or @edwardando?

**Comment by vuhlmann** [comment]
Again an excellent suggestion that I fully endorse. I would prefer `arc_length(start=5, stop=10)` because I can already imagine cursing myself after 3hr of hunting down a bug only to realize that I forgot the stop and start argument were reversed in this function...better to be explicit I think.

**Comment by faymanns** [comment]
Ok, I think there is an easy fix for that problem. We can just swap `start` and `stop` in the function if `start > stop`.
That way it doesn't matter in which order you specify `start` and `stop` when you call the function.

**Comment by faymanns** [comment]
Implemented in 295de5068eb9f9089d8f7b64fa6e141987918e10.
